# Generated by Django 4.0.6 on 2022-09-01 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TBLDetai',
            fields=[
                ('madt', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tendt', models.CharField(max_length=30)),
                ('kinhphi', models.IntegerField()),
                ('noithuctap', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_de_tai',
            },
        ),
        migrations.CreateModel(
            name='TBLGiangVien',
            fields=[
                ('magv', models.IntegerField(primary_key=True, serialize=False)),
                ('hotengv', models.CharField(max_length=30)),
                ('luong', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'tbl_giang_vien',
            },
        ),
        migrations.CreateModel(
            name='TBLKhoa',
            fields=[
                ('makhoa', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False)),
                ('tenkhoa', models.CharField(blank=True, max_length=30)),
                ('dienthoai', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'db_table': 'tbl_khoa',
            },
        ),
        migrations.CreateModel(
            name='TBLSinhVien',
            fields=[
                ('masv', models.IntegerField(primary_key=True, serialize=False)),
                ('hoten', models.CharField(max_length=30)),
                ('namsinh', models.IntegerField()),
                ('quequan', models.CharField(max_length=30)),
                ('makhoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoapi.tblkhoa')),
            ],
            options={
                'db_table': 'tbl_sinh_vien',
            },
        ),
        migrations.CreateModel(
            name='TBLHuongDan',
            fields=[
                ('masv', models.IntegerField(primary_key=True, serialize=False)),
                ('ketqua', models.DecimalField(decimal_places=2, max_digits=5)),
                ('madt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoapi.tbldetai')),
                ('magv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoapi.tblgiangvien')),
            ],
            options={
                'db_table': 'tbl_huong_dan',
            },
        ),
        migrations.AddField(
            model_name='tblgiangvien',
            name='makhoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoapi.tblkhoa'),
        ),
    ]
